### ISSUE TITLE
Deployment Error....

### ISSUE THREAD

**Issue by missemily2022** [jusidama18/Gist-Telegram-Bot#3]
![IMG_20220802_020017](https://user-images.githubusercontent.com/97376138/182241741-8be6086c-3869-436a-b229-49edd25be11e.jpg)

**Comment by missemily2022** [comment]
![image](https://user-images.githubusercontent.com/97376138/182352868-1acb06c6-c116-47bf-a713-a5306781d1b6.png)
Now a New Error has come where text is not pasted to Gist

**Comment by jusidama18** [comment]
> ![image](https://user-images.githubusercontent.com/97376138/182352868-1acb06c6-c116-47bf-a713-a5306781d1b6.png) Now a New Error has come where text is not pasted to Gist

try again now

**Comment by missemily2022** [comment]
> > ![image](https://user-images.githubusercontent.com/97376138/182352868-1acb06c6-c116-47bf-a713-a5306781d1b6.png) Now a New Error has come where text is not pasted to Gist
> 
> try again now

![image](https://user-images.githubusercontent.com/97376138/183039954-b9bde362-f1fa-4f66-a251-7ba8371d790b.png)

**Comment by jusidama18** [comment]
> > > ![image](https://user-images.githubusercontent.com/97376138/182352868-1acb06c6-c116-47bf-a713-a5306781d1b6.png) Now a New Error has come where text is not pasted to Gist
> > 
> > 
> > try again now
> 
> ![image](https://user-images.githubusercontent.com/97376138/183039954-b9bde362-f1fa-4f66-a251-7ba8371d790b.png)

done

**Comment by missemily2022** [comment]
@jusidama18 Now See This
![IMG_20220806_080112](https://user-images.githubusercontent.com/97376138/183230146-89fe1fe7-1047-46dd-844b-a86a7697efe6.jpg)
![IMG_20220806_080125](https://user-images.githubusercontent.com/97376138/183230148-6f045cc4-f316-42f4-96f6-7b7ade2f94f2.jpg)

**Comment by jusidama18** [comment]
> @jusidama18 Now See This ![IMG_20220806_080112](https://user-images.githubusercontent.com/97376138/183230146-89fe1fe7-1047-46dd-844b-a86a7697efe6.jpg) ![IMG_20220806_080125](https://user-images.githubusercontent.com/97376138/183230148-6f045cc4-f316-42f4-96f6-7b7ade2f94f2.jpg)

try

**Comment by missemily2022** [comment]
@jusidama18 Working Now
Thanks :)
